# Generated by Django 2.1.5 on 2019-07-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=1000000000000000000)),
                ('pdf', models.FileField(default='books_pdf/None.pdf', upload_to='books_pdf/')),
            ],
        ),
    ]
